# bank-additional

In [1]:
# Importing the libraries 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

# Ignore harmless warnings 

import warnings 
warnings.filterwarnings("ignore")

import pandasql as psql

# pip install pandasql

In [2]:
# Load the Universal Bank Marketing Campaign (BMC) data

BMCdata = pd.read_csv(r"D:\iiit notes\Programming\AI\Internship practice\40 seasion 13-jul-2021\bank-additional-full-V1.0.csv", header=0)
BMCdata.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,Deposit
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [3]:
# displaying the BMC dataset

BMCdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  Deposit         41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [4]:
# Replace target variable 'Deposit', 'Yes' to 1 and 'No' to 0 and # convert the 'y' to integer value.

BMCdata['Deposit'] = BMCdata['Deposit'].str.replace('yes', '1')
BMCdata['Deposit'] = BMCdata['Deposit'].str.replace('no', '0')
BMCdata['Deposit'] = BMCdata['Deposit'].astype(int)

In [5]:
# Count the target or dependent variable by '0' & '1' and 
# their proportion (> 10 : 1, then the dataset is imbalance dataset)

BMCdata_count = BMCdata.Deposit.value_counts()
print('Class 0:', BMCdata_count[0])
print('Class 1:', BMCdata_count[1])
print('Proportion:', round(BMCdata_count[0] / BMCdata_count[1], 2), ': 1')
print('Total CC Trans:', len(BMCdata))

Class 0: 36548
Class 1: 4640
Proportion: 7.88 : 1
Total CC Trans: 41188

In [6]:
# Dealing the Duplicate values 

BMCdata_dup = BMCdata[BMCdata.duplicated(keep='last')]
BMCdata_dup

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,Deposit
1265,39,blue-collar,married,basic.6y,no,no,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,0
12260,36,retired,married,unknown,no,no,no,telephone,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.966,5228.1,0
14155,27,technician,single,professional.course,no,no,no,cellular,jul,mon,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,0
16819,47,technician,divorced,high.school,no,yes,no,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,0
18464,32,technician,single,professional.course,no,yes,no,cellular,jul,thu,...,1,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,0
20072,55,services,married,high.school,unknown,no,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,0
20531,41,technician,married,professional.course,no,yes,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,0
25183,39,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,0
28476,24,services,single,high.school,no,yes,no,cellular,apr,tue,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.423,5099.1,0
32505,35,admin.,married,university.degree,no,yes,no,cellular,may,fri,...,4,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,0
36950,45,admin.,married,university.degree,no,no,no,cellular,jul,thu,...,1,999,0,nonexistent,-2.9,92.469,-33.6,1.072,5076.2,1
38255,71,retired,single,university.degree,no,no,no,telephone,oct,tue,...,1,999,0,nonexistent,-3.4,92.431,-26.9,0.742,5017.5,0

In [7]:
# Remove the identified duplicate records 

BMCdata = BMCdata.drop_duplicates()
BMCdata.shape

(41176, 21)

In [8]:
# Replace target variable 'housing', and convert the 'housing' to integer value.

BMCdata['housing'] = BMCdata['housing'].str.replace('yes', '1')
BMCdata['housing'] = BMCdata['housing'].str.replace('no', '0')
BMCdata['housing'] = BMCdata['housing'].str.replace('unk0wn', '2')
BMCdata['housing'] = BMCdata['housing'].astype(int)

In [9]:
# Replace target variable 'loan', andconvert the 'loan' to integer value.

BMCdata['loan'] = BMCdata['loan'].str.replace('yes', '1')
BMCdata['loan'] = BMCdata['loan'].str.replace('no', '0')
BMCdata['loan'] = BMCdata['loan'].str.replace('unk0wn', '2')
BMCdata['loan'] = BMCdata['loan'].astype(int)

In [10]:
# Replace the variable 'education', convert the 'education' to integer value.

BMCdata['education'] = BMCdata['education'].str.replace('illiterate', '1')
BMCdata['education'] = BMCdata['education'].str.replace('unknown', '1')
BMCdata['education'] = BMCdata['education'].str.replace('basic.4y', '2')
BMCdata['education'] = BMCdata['education'].str.replace('basic.6y', '2')
BMCdata['education'] = BMCdata['education'].str.replace('basic.9y', '2')
BMCdata['education'] = BMCdata['education'].str.replace('high.school', '3')
BMCdata['education'] = BMCdata['education'].str.replace('professional.course', '4')
BMCdata['education'] = BMCdata['education'].str.replace('university.degree', '5')
BMCdata['education'] = BMCdata['education'].astype(int)

In [11]:
# Replace variable 'marital', and convert the 'marital' to integer value.

BMCdata['marital'] = BMCdata['marital'].str.replace('single', '1')
BMCdata['marital'] = BMCdata['marital'].str.replace('married', '2')
BMCdata['marital'] = BMCdata['marital'].str.replace('divorced', '3')
BMCdata['marital'] = BMCdata['marital'].str.replace('unknown', '4')
BMCdata['marital'] = BMCdata['marital'].astype(int)

In [12]:
# Replace variable 'default', and convert the 'default' to integer value.

BMCdata['default'] = BMCdata['default'].str.replace('yes', '1')
BMCdata['default'] = BMCdata['default'].str.replace('no', '0')
BMCdata['default'] = BMCdata['default'].str.replace('unk0wn', '2')
BMCdata['default'] = BMCdata['default'].astype(int)

In [13]:
# Replace variable 'contact', and convert the 'contact' to integer value.

BMCdata['contact'] = BMCdata['contact'].str.replace('telephone', '1')
BMCdata['contact'] = BMCdata['contact'].str.replace('cellular', '2')
BMCdata['contact'] = BMCdata['contact'].astype(int)

In [14]:
# Replace variable 'day_of_week', and convert the 'day_of_week' to integer value.

BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('mon', '1')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('tue', '2')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('wed', '3')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('thu', '4')
BMCdata['day_of_week'] = BMCdata['day_of_week'].str.replace('fri', '5')
BMCdata['day_of_week'] = BMCdata['day_of_week'].astype(int)

In [15]:
# Replace variable 'month', and convert the 'month' to integer value.

BMCdata['month'] = BMCdata['month'].str.replace('mar', '3')
BMCdata['month'] = BMCdata['month'].str.replace('apr', '4')
BMCdata['month'] = BMCdata['month'].str.replace('may', '5')
BMCdata['month'] = BMCdata['month'].str.replace('jun', '6')
BMCdata['month'] = BMCdata['month'].str.replace('jul', '7')
BMCdata['month'] = BMCdata['month'].str.replace('aug', '8')
BMCdata['month'] = BMCdata['month'].str.replace('sep', '9')
BMCdata['month'] = BMCdata['month'].str.replace('oct', '10')
BMCdata['month'] = BMCdata['month'].str.replace('nov', '11')
BMCdata['month'] = BMCdata['month'].str.replace('dec', '12')
BMCdata['month'] = BMCdata['month'].astype(int)

In [16]:
# Replace variable 'poutcome', and convert the 'poutcome' to integer value.

BMCdata['poutcome'] = BMCdata['poutcome'].str.replace('nonexistent', '0')
BMCdata['poutcome'] = BMCdata['poutcome'].str.replace('failure', '1')
BMCdata['poutcome'] = BMCdata['poutcome'].str.replace('success', '2')
BMCdata['poutcome'] = BMCdata['poutcome'].astype(int)

In [17]:
BMCdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41176 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41176 non-null  int64
 1   job             41176 non-null  object
 2   marital         41176 non-null  int32
 3   education       41176 non-null  int32
 4   default         41176 non-null  int32
 5   housing         41176 non-null  int32
 6   loan            41176 non-null  int32
 7   contact         41176 non-null  int32
 8   month           41176 non-null  int32
 9   day_of_week     41176 non-null  int32
 10  duration        41176 non-null  int64
 11  campaign        41176 non-null  int64
 12  pdays           41176 non-null  int64
 13  previous        41176 non-null  int64
 14  poutcome        41176 non-null  int32
 15  emp.var.rate    41176 non-null  float64
 16  cons.price.idx  41176 non-null  float64
 17  cons.conf.idx   41176 non-null  float64
 18  euribor3m       41176 non-null  float64
 19  nr.employed     41176 non-null  float64
 20  Deposit         41176 non-null  int32
dtypes: float64(5), int32(10), int64(5), object(1)
memory usage: 5.3+ MB

In [18]:
del BMCdata['job']

In [19]:
# Identify the independt and dependent variables

from sklearn.model_selection import train_test_split

x = BMCdata.drop('Deposit', axis=1)
y = BMCdata['Deposit']

In [20]:
# Splitting the dataset into train and test 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.40, random_state = 42,
                                                   stratify=y) 
x_test_f1 = x_test.copy()

In [21]:
# we use Standardization to remove the mean and scale to unit variance

from sklearn.preprocessing import StandardScaler

stdscaler = StandardScaler()

x_train = stdscaler.fit_transform(x_train)
x_train = pd.DataFrame(x_train)

x_test = stdscaler.fit_transform(x_test)
x_test = pd.DataFrame(x_test)

# Linear Kernel

In [22]:
# Training the SVM algorithm for classification problem

from sklearn.svm import SVC

BMCdataSVM = SVC(C=1.0, kernel='linear', degree=3, gamma='scale', coef0=0.0, shrinking=True, 
                 probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, 
                 max_iter=- 1, decision_function_shape='ovr', break_ties=False, random_state=42)

BMCdataSVM = BMCdataSVM.fit(x_train, y_train)

In [23]:
# Predictions with test data

y_pred = BMCdataSVM.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y_pred), 3))

Confusion matrix :
 [[  511  1345]
 [  299 14316]]
Outcome Values :
 511 1345 299 14316
Classification report :
               precision    recall  f1-score   support

           1       0.63      0.28      0.38      1856
           0       0.91      0.98      0.95     14615

    accuracy                           0.90     16471
   macro avg       0.77      0.63      0.66     16471
weighted avg       0.88      0.90      0.88     16471

Accuracy : 90.0 %
Precision : 63.1 %
Recall : 27.5 %
F1 Score : 0.383
Balanced Accuracy : 62.8 %
MCC 0.373
roc_auc_score: 0.627

# Polynomial Kernel

In [24]:
# Training the SVM algorithm

from sklearn.svm import SVC

BMCdataSVMPoly = SVC(kernel='poly', degree=2)
BMCdataSVMPoly.fit(x_train, y_train)

# Predicting the values

y1_pred = BMCdataSVMPoly.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y1_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y1_pred), 3))

Confusion matrix :
 [[  469  1387]
 [  192 14423]]
Outcome Values :
 469 1387 192 14423
Classification report :
               precision    recall  f1-score   support

           1       0.71      0.25      0.37      1856
           0       0.91      0.99      0.95     14615

    accuracy                           0.90     16471
   macro avg       0.81      0.62      0.66     16471
weighted avg       0.89      0.90      0.88     16471

Accuracy : 90.4 %
Precision : 71.0 %
Recall : 25.3 %
F1 Score : 0.373
Balanced Accuracy : 62.0 %
MCC 0.386
roc_auc_score: 0.62

# Gaussian Kernel

In [25]:
# Training the SVM algorithm

from sklearn.svm import SVC

BMCdataSVMGaussian = SVC(kernel='rbf', random_state = 1, class_weight='balanced')
BMCdataSVMGaussian.fit(x_train, y_train)

# Predicting the values

y2_pred = BMCdataSVMGaussian.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y2_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y2_pred), 3))

Confusion matrix :
 [[ 1723   133]
 [ 2346 12269]]
Outcome Values :
 1723 133 2346 12269
Classification report :
               precision    recall  f1-score   support

           1       0.42      0.93      0.58      1856
           0       0.99      0.84      0.91     14615

    accuracy                           0.85     16471
   macro avg       0.71      0.88      0.74     16471
weighted avg       0.93      0.85      0.87     16471

Accuracy : 84.9 %
Precision : 42.3 %
Recall : 92.8 %
F1 Score : 0.582
Balanced Accuracy : 88.4 %
MCC 0.563
roc_auc_score: 0.884

# Sigmoid Kernel

In [26]:
# Training the SVM algorithm

from sklearn.svm import SVC

BMCdataSVMSig = SVC(kernel='sigmoid', random_state = 1, class_weight='balanced')
BMCdataSVMSig.fit(x_train, y_train)

# Predicting the values

y3_pred = BMCdataSVMSig.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix

# actual values

actual = y_test

# predicted values
predicted = y3_pred

# confusion matrix

matrix = confusion_matrix(actual, predicted, labels=[1, 0], sample_weight=None, normalize=None,)
print('Confusion matrix : \n', matrix)

# outcome values order in sklearn

tp,fn, fp, tn = confusion_matrix(actual, predicted, labels=[1,0]).reshape(-1)

print('Outcome Values : \n', tp, fn, fp, tn)

# classification report for precision, recall f1-score and accuracy

matrix = classification_report(actual,predicted,labels=[1,0])
print('Classification report : \n', matrix)

# calculating the metrics

sensitivity = round(tp/(tp+fn), 3) 

specificity = round(tn/(tn+fp), 3)

accuracy = round((tp+tn)/(tp+fp+tn+fn), 3)
balanced_accuracy = round((sensitivity+specificity)/2, 3)
precision = round(tp/(tp+fp), 3)
f1Score = round((2*tp/(2*tp + fp +fn)), 3);

# Mathews Correlatin coefficient (MCC). Range of values of MCC lie between -1 to +1
# A model with a score of +1 is a perfect model and -1 is a poor model

from math import sqrt

m = (tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)

MCC = round(((tp* tn) - (fp * fn)) / sqrt(m), 3)

print('Accuracy :', round(accuracy*100, 2), '%')
print('Precision :', round(precision*100, 2), '%')
print('Recall :', round(sensitivity*100, 2), '%')
print('F1 Score :', f1Score)
print('Balanced Accuracy :', round(balanced_accuracy*100, 2), '%')
print('MCC', MCC)

from sklearn.metrics import roc_curve, roc_auc_score

# Area under ROC curve 
print('roc_auc_score:', round(roc_auc_score(y_test, y3_pred), 3))

Confusion matrix :
 [[ 1337   519]
 [ 3813 10802]]
Outcome Values :
 1337 519 3813 10802
Classification report :
               precision    recall  f1-score   support

           1       0.26      0.72      0.38      1856
           0       0.95      0.74      0.83     14615

    accuracy                           0.74     16471
   macro avg       0.61      0.73      0.61     16471
weighted avg       0.88      0.74      0.78     16471

Accuracy : 73.7 %
Precision : 26.0 %
Recall : 72.0 %
F1 Score : 0.382
Balanced Accuracy : 73.0 %
MCC 0.313
roc_auc_score: 0.73